/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SessionId = IDL.Nat;
export const Timestamp = IDL.Int;
export const SkillLevel = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'learningGoals' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'skillLevel' : SkillLevel,
});
export const UserId = IDL.Principal;
export const Badge = IDL.Variant({
  'streak' : IDL.Null,
  'perfectScore' : IDL.Null,
  'quizMaster' : IDL.Null,
  'firstSteps' : IDL.Null,
});
export const TopicId = IDL.Nat;
export const UserProgress = IDL.Record({
  'userId' : UserId,
  'badges' : IDL.Vec(Badge),
  'topicsCompleted' : IDL.Vec(TopicId),
  'longestStreak' : IDL.Nat,
  'totalPoints' : IDL.Nat,
  'lastActivityAt' : Timestamp,
  'currentStreak' : IDL.Nat,
});
export const QuizId = IDL.Nat;
export const QuizAttempt = IDL.Record({
  'id' : IDL.Nat,
  'completedAt' : Timestamp,
  'userId' : UserId,
  'answers' : IDL.Vec(IDL.Nat),
  'score' : IDL.Nat,
  'pointsEarned' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'quizId' : QuizId,
  'topicId' : TopicId,
  'accuracy' : IDL.Nat,
});
export const MessageRole = IDL.Variant({
  'user' : IDL.Null,
  'assistant' : IDL.Null,
});
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'role' : MessageRole,
  'timestamp' : Timestamp,
});
export const LearningSession = IDL.Record({
  'id' : SessionId,
  'startedAt' : Timestamp,
  'messages' : IDL.Vec(ChatMessage),
  'userId' : UserId,
  'isActive' : IDL.Bool,
  'updatedAt' : Timestamp,
  'topicId' : TopicId,
});
export const WeakArea = IDL.Record({
  'averageAccuracy' : IDL.Nat,
  'attemptCount' : IDL.Nat,
  'topicTitle' : IDL.Text,
  'topicId' : TopicId,
});
export const ProgressSummary = IDL.Record({
  'averageAccuracy' : IDL.Nat,
  'badges' : IDL.Vec(Badge),
  'quizAttemptCount' : IDL.Nat,
  'topicsCompletedCount' : IDL.Nat,
  'totalPoints' : IDL.Nat,
  'weakAreas' : IDL.Vec(WeakArea),
  'currentStreak' : IDL.Nat,
});
export const QuizOption = IDL.Record({ 'id' : IDL.Nat, 'text' : IDL.Text });
export const QuizQuestion = IDL.Record({
  'id' : IDL.Nat,
  'correctOptionId' : IDL.Nat,
  'question' : IDL.Text,
  'explanation' : IDL.Text,
  'options' : IDL.Vec(QuizOption),
});
export const Quiz = IDL.Record({
  'id' : QuizId,
  'createdAt' : Timestamp,
  'questions' : IDL.Vec(QuizQuestion),
  'topicId' : TopicId,
});
export const DifficultyLevel = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'medium' : IDL.Null,
});
export const Topic = IDL.Record({
  'id' : TopicId,
  'title' : IDL.Text,
  'difficulty' : DifficultyLevel,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const TopicCompletion = IDL.Record({
  'completedAt' : Timestamp,
  'userId' : UserId,
  'pointsEarned' : IDL.Nat,
  'topicId' : TopicId,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'closeSession' : IDL.Func([SessionId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyProgress' : IDL.Func([], [IDL.Opt(UserProgress)], ['query']),
  'getMyQuizAttempts' : IDL.Func([], [IDL.Vec(QuizAttempt)], ['query']),
  'getOrCreateSession' : IDL.Func([TopicId], [LearningSession], []),
  'getProgressSummary' : IDL.Func([], [ProgressSummary], ['query']),
  'getQuizForTopic' : IDL.Func([TopicId], [IDL.Opt(Quiz)], ['query']),
  'getRecommendedTopics' : IDL.Func([], [IDL.Vec(Topic)], ['query']),
  'getSessionHistory' : IDL.Func([TopicId], [IDL.Vec(ChatMessage)], ['query']),
  'getTopic' : IDL.Func([TopicId], [IDL.Opt(Topic)], ['query']),
  'getTopicCompletionStatus' : IDL.Func(
      [TopicId],
      [IDL.Opt(TopicCompletion)],
      ['query'],
    ),
  'getTopicQuizAttempts' : IDL.Func(
      [TopicId],
      [IDL.Vec(QuizAttempt)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeakAreas' : IDL.Func([], [IDL.Vec(WeakArea)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listTopics' : IDL.Func([], [IDL.Vec(Topic)], ['query']),
  'markTopicCompleted' : IDL.Func([TopicId], [IDL.Nat], []),
  'saveAiGeneratedQuiz' : IDL.Func(
      [TopicId, IDL.Vec(QuizQuestion)],
      [Quiz],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([TopicId, IDL.Text], [IDL.Text], []),
  'submitQuizAttempt' : IDL.Func([QuizId, IDL.Vec(IDL.Nat)], [QuizAttempt], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SessionId = IDL.Nat;
  const Timestamp = IDL.Int;
  const SkillLevel = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'learningGoals' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'skillLevel' : SkillLevel,
  });
  const UserId = IDL.Principal;
  const Badge = IDL.Variant({
    'streak' : IDL.Null,
    'perfectScore' : IDL.Null,
    'quizMaster' : IDL.Null,
    'firstSteps' : IDL.Null,
  });
  const TopicId = IDL.Nat;
  const UserProgress = IDL.Record({
    'userId' : UserId,
    'badges' : IDL.Vec(Badge),
    'topicsCompleted' : IDL.Vec(TopicId),
    'longestStreak' : IDL.Nat,
    'totalPoints' : IDL.Nat,
    'lastActivityAt' : Timestamp,
    'currentStreak' : IDL.Nat,
  });
  const QuizId = IDL.Nat;
  const QuizAttempt = IDL.Record({
    'id' : IDL.Nat,
    'completedAt' : Timestamp,
    'userId' : UserId,
    'answers' : IDL.Vec(IDL.Nat),
    'score' : IDL.Nat,
    'pointsEarned' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'quizId' : QuizId,
    'topicId' : TopicId,
    'accuracy' : IDL.Nat,
  });
  const MessageRole = IDL.Variant({
    'user' : IDL.Null,
    'assistant' : IDL.Null,
  });
  const ChatMessage = IDL.Record({
    'content' : IDL.Text,
    'role' : MessageRole,
    'timestamp' : Timestamp,
  });
  const LearningSession = IDL.Record({
    'id' : SessionId,
    'startedAt' : Timestamp,
    'messages' : IDL.Vec(ChatMessage),
    'userId' : UserId,
    'isActive' : IDL.Bool,
    'updatedAt' : Timestamp,
    'topicId' : TopicId,
  });
  const WeakArea = IDL.Record({
    'averageAccuracy' : IDL.Nat,
    'attemptCount' : IDL.Nat,
    'topicTitle' : IDL.Text,
    'topicId' : TopicId,
  });
  const ProgressSummary = IDL.Record({
    'averageAccuracy' : IDL.Nat,
    'badges' : IDL.Vec(Badge),
    'quizAttemptCount' : IDL.Nat,
    'topicsCompletedCount' : IDL.Nat,
    'totalPoints' : IDL.Nat,
    'weakAreas' : IDL.Vec(WeakArea),
    'currentStreak' : IDL.Nat,
  });
  const QuizOption = IDL.Record({ 'id' : IDL.Nat, 'text' : IDL.Text });
  const QuizQuestion = IDL.Record({
    'id' : IDL.Nat,
    'correctOptionId' : IDL.Nat,
    'question' : IDL.Text,
    'explanation' : IDL.Text,
    'options' : IDL.Vec(QuizOption),
  });
  const Quiz = IDL.Record({
    'id' : QuizId,
    'createdAt' : Timestamp,
    'questions' : IDL.Vec(QuizQuestion),
    'topicId' : TopicId,
  });
  const DifficultyLevel = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Topic = IDL.Record({
    'id' : TopicId,
    'title' : IDL.Text,
    'difficulty' : DifficultyLevel,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const TopicCompletion = IDL.Record({
    'completedAt' : Timestamp,
    'userId' : UserId,
    'pointsEarned' : IDL.Nat,
    'topicId' : TopicId,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'closeSession' : IDL.Func([SessionId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyProgress' : IDL.Func([], [IDL.Opt(UserProgress)], ['query']),
    'getMyQuizAttempts' : IDL.Func([], [IDL.Vec(QuizAttempt)], ['query']),
    'getOrCreateSession' : IDL.Func([TopicId], [LearningSession], []),
    'getProgressSummary' : IDL.Func([], [ProgressSummary], ['query']),
    'getQuizForTopic' : IDL.Func([TopicId], [IDL.Opt(Quiz)], ['query']),
    'getRecommendedTopics' : IDL.Func([], [IDL.Vec(Topic)], ['query']),
    'getSessionHistory' : IDL.Func(
        [TopicId],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getTopic' : IDL.Func([TopicId], [IDL.Opt(Topic)], ['query']),
    'getTopicCompletionStatus' : IDL.Func(
        [TopicId],
        [IDL.Opt(TopicCompletion)],
        ['query'],
      ),
    'getTopicQuizAttempts' : IDL.Func(
        [TopicId],
        [IDL.Vec(QuizAttempt)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeakAreas' : IDL.Func([], [IDL.Vec(WeakArea)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listTopics' : IDL.Func([], [IDL.Vec(Topic)], ['query']),
    'markTopicCompleted' : IDL.Func([TopicId], [IDL.Nat], []),
    'saveAiGeneratedQuiz' : IDL.Func(
        [TopicId, IDL.Vec(QuizQuestion)],
        [Quiz],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([TopicId, IDL.Text], [IDL.Text], []),
    'submitQuizAttempt' : IDL.Func(
        [QuizId, IDL.Vec(IDL.Nat)],
        [QuizAttempt],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };