/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Badge = { 'streak' : null } |
  { 'perfectScore' : null } |
  { 'quizMaster' : null } |
  { 'firstSteps' : null };
export interface ChatMessage {
  'content' : string,
  'role' : MessageRole,
  'timestamp' : Timestamp,
}
export type DifficultyLevel = { 'easy' : null } |
  { 'hard' : null } |
  { 'medium' : null };
export interface LearningSession {
  'id' : SessionId,
  'startedAt' : Timestamp,
  'messages' : Array<ChatMessage>,
  'userId' : UserId,
  'isActive' : boolean,
  'updatedAt' : Timestamp,
  'topicId' : TopicId,
}
export type MessageRole = { 'user' : null } |
  { 'assistant' : null };
export interface ProgressSummary {
  'averageAccuracy' : bigint,
  'badges' : Array<Badge>,
  'quizAttemptCount' : bigint,
  'topicsCompletedCount' : bigint,
  'totalPoints' : bigint,
  'weakAreas' : Array<WeakArea>,
  'currentStreak' : bigint,
}
export interface Quiz {
  'id' : QuizId,
  'createdAt' : Timestamp,
  'questions' : Array<QuizQuestion>,
  'topicId' : TopicId,
}
export interface QuizAttempt {
  'id' : bigint,
  'completedAt' : Timestamp,
  'userId' : UserId,
  'answers' : Array<bigint>,
  'score' : bigint,
  'pointsEarned' : bigint,
  'totalQuestions' : bigint,
  'quizId' : QuizId,
  'topicId' : TopicId,
  'accuracy' : bigint,
}
export type QuizId = bigint;
export interface QuizOption { 'id' : bigint, 'text' : string }
export interface QuizQuestion {
  'id' : bigint,
  'correctOptionId' : bigint,
  'question' : string,
  'explanation' : string,
  'options' : Array<QuizOption>,
}
export type SessionId = bigint;
export type SkillLevel = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'advanced' : null };
export type Timestamp = bigint;
export interface Topic {
  'id' : TopicId,
  'title' : string,
  'difficulty' : DifficultyLevel,
  'createdAt' : Timestamp,
  'description' : string,
  'category' : string,
}
export interface TopicCompletion {
  'completedAt' : Timestamp,
  'userId' : UserId,
  'pointsEarned' : bigint,
  'topicId' : TopicId,
}
export type TopicId = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserProfile {
  'learningGoals' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'skillLevel' : SkillLevel,
}
export interface UserProgress {
  'userId' : UserId,
  'badges' : Array<Badge>,
  'topicsCompleted' : Array<TopicId>,
  'longestStreak' : bigint,
  'totalPoints' : bigint,
  'lastActivityAt' : Timestamp,
  'currentStreak' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeakArea {
  'averageAccuracy' : bigint,
  'attemptCount' : bigint,
  'topicTitle' : string,
  'topicId' : TopicId,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'closeSession' : ActorMethod<[SessionId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyProgress' : ActorMethod<[], [] | [UserProgress]>,
  'getMyQuizAttempts' : ActorMethod<[], Array<QuizAttempt>>,
  'getOrCreateSession' : ActorMethod<[TopicId], LearningSession>,
  'getProgressSummary' : ActorMethod<[], ProgressSummary>,
  'getQuizForTopic' : ActorMethod<[TopicId], [] | [Quiz]>,
  'getRecommendedTopics' : ActorMethod<[], Array<Topic>>,
  'getSessionHistory' : ActorMethod<[TopicId], Array<ChatMessage>>,
  'getTopic' : ActorMethod<[TopicId], [] | [Topic]>,
  'getTopicCompletionStatus' : ActorMethod<[TopicId], [] | [TopicCompletion]>,
  'getTopicQuizAttempts' : ActorMethod<[TopicId], Array<QuizAttempt>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeakAreas' : ActorMethod<[], Array<WeakArea>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listTopics' : ActorMethod<[], Array<Topic>>,
  'markTopicCompleted' : ActorMethod<[TopicId], bigint>,
  'saveAiGeneratedQuiz' : ActorMethod<[TopicId, Array<QuizQuestion>], Quiz>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[TopicId, string], string>,
  'submitQuizAttempt' : ActorMethod<[QuizId, Array<bigint>], QuizAttempt>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];