/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ProgressSummary {
    averageAccuracy: bigint;
    badges: Array<Badge>;
    quizAttemptCount: bigint;
    topicsCompletedCount: bigint;
    totalPoints: bigint;
    weakAreas: Array<WeakArea>;
    currentStreak: bigint;
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface QuizQuestion {
    id: bigint;
    correctOptionId: bigint;
    question: string;
    explanation: string;
    options: Array<QuizOption>;
}
export interface Quiz {
    id: QuizId;
    createdAt: Timestamp;
    questions: Array<QuizQuestion>;
    topicId: TopicId;
}
export type SessionId = bigint;
export interface UserProgress {
    userId: UserId;
    badges: Array<Badge>;
    topicsCompleted: Array<TopicId>;
    longestStreak: bigint;
    totalPoints: bigint;
    lastActivityAt: Timestamp;
    currentStreak: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface LearningSession {
    id: SessionId;
    startedAt: Timestamp;
    messages: Array<ChatMessage>;
    userId: UserId;
    isActive: boolean;
    updatedAt: Timestamp;
    topicId: TopicId;
}
export type UserId = Principal;
export type TopicId = bigint;
export interface QuizAttempt {
    id: bigint;
    completedAt: Timestamp;
    userId: UserId;
    answers: Array<bigint>;
    score: bigint;
    pointsEarned: bigint;
    totalQuestions: bigint;
    quizId: QuizId;
    topicId: TopicId;
    accuracy: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Topic {
    id: TopicId;
    title: string;
    difficulty: DifficultyLevel;
    createdAt: Timestamp;
    description: string;
    category: string;
}
export interface ChatMessage {
    content: string;
    role: MessageRole;
    timestamp: Timestamp;
}
export interface TopicCompletion {
    completedAt: Timestamp;
    userId: UserId;
    pointsEarned: bigint;
    topicId: TopicId;
}
export interface QuizOption {
    id: bigint;
    text: string;
}
export interface WeakArea {
    averageAccuracy: bigint;
    attemptCount: bigint;
    topicTitle: string;
    topicId: TopicId;
}
export interface UserProfile {
    learningGoals: string;
    name: string;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    skillLevel: SkillLevel;
}
export type QuizId = bigint;
export enum Badge {
    streak = "streak",
    perfectScore = "perfectScore",
    quizMaster = "quizMaster",
    firstSteps = "firstSteps"
}
export enum DifficultyLevel {
    easy = "easy",
    hard = "hard",
    medium = "medium"
}
export enum MessageRole {
    user = "user",
    assistant = "assistant"
}
export enum SkillLevel {
    intermediate = "intermediate",
    beginner = "beginner",
    advanced = "advanced"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    closeSession(sessionId: SessionId): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMyProgress(): Promise<UserProgress | null>;
    getMyQuizAttempts(): Promise<Array<QuizAttempt>>;
    getOrCreateSession(topicId: TopicId): Promise<LearningSession>;
    getProgressSummary(): Promise<ProgressSummary>;
    getQuizForTopic(topicId: TopicId): Promise<Quiz | null>;
    getRecommendedTopics(): Promise<Array<Topic>>;
    getSessionHistory(topicId: TopicId): Promise<Array<ChatMessage>>;
    getTopic(topicId: TopicId): Promise<Topic | null>;
    getTopicCompletionStatus(topicId: TopicId): Promise<TopicCompletion | null>;
    getTopicQuizAttempts(topicId: TopicId): Promise<Array<QuizAttempt>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWeakAreas(): Promise<Array<WeakArea>>;
    isCallerAdmin(): Promise<boolean>;
    listTopics(): Promise<Array<Topic>>;
    markTopicCompleted(topicId: TopicId): Promise<bigint>;
    saveAiGeneratedQuiz(topicId: TopicId, questions: Array<QuizQuestion>): Promise<Quiz>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendMessage(topicId: TopicId, userMessage: string): Promise<string>;
    submitQuizAttempt(quizId: QuizId, answers: Array<bigint>): Promise<QuizAttempt>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { Badge as _Badge, ChatMessage as _ChatMessage, DifficultyLevel as _DifficultyLevel, LearningSession as _LearningSession, MessageRole as _MessageRole, ProgressSummary as _ProgressSummary, Quiz as _Quiz, SessionId as _SessionId, SkillLevel as _SkillLevel, Timestamp as _Timestamp, Topic as _Topic, TopicCompletion as _TopicCompletion, TopicId as _TopicId, UserId as _UserId, UserProfile as _UserProfile, UserProgress as _UserProgress, UserRole as _UserRole, WeakArea as _WeakArea } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async closeSession(arg0: SessionId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.closeSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.closeSession(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProgress(): Promise<UserProgress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProgress();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProgress();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyQuizAttempts(): Promise<Array<QuizAttempt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyQuizAttempts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyQuizAttempts();
            return result;
        }
    }
    async getOrCreateSession(arg0: TopicId): Promise<LearningSession> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrCreateSession(arg0);
                return from_candid_LearningSession_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrCreateSession(arg0);
            return from_candid_LearningSession_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProgressSummary(): Promise<ProgressSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgressSummary();
                return from_candid_ProgressSummary_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgressSummary();
            return from_candid_ProgressSummary_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuizForTopic(arg0: TopicId): Promise<Quiz | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizForTopic(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizForTopic(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecommendedTopics(): Promise<Array<Topic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecommendedTopics();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecommendedTopics();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSessionHistory(arg0: TopicId): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionHistory(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionHistory(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopic(arg0: TopicId): Promise<Topic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopic(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopic(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopicCompletionStatus(arg0: TopicId): Promise<TopicCompletion | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopicCompletionStatus(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopicCompletionStatus(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopicQuizAttempts(arg0: TopicId): Promise<Array<QuizAttempt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopicQuizAttempts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopicQuizAttempts(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeakAreas(): Promise<Array<WeakArea>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeakAreas();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeakAreas();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listTopics(): Promise<Array<Topic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTopics();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTopics();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async markTopicCompleted(arg0: TopicId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.markTopicCompleted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markTopicCompleted(arg0);
            return result;
        }
    }
    async saveAiGeneratedQuiz(arg0: TopicId, arg1: Array<QuizQuestion>): Promise<Quiz> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAiGeneratedQuiz(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAiGeneratedQuiz(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n33(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n33(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendMessage(arg0: TopicId, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async submitQuizAttempt(arg0: QuizId, arg1: Array<bigint>): Promise<QuizAttempt> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuizAttempt(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuizAttempt(arg0, arg1);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_Badge_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Badge): Badge {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ChatMessage_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatMessage): ChatMessage {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_DifficultyLevel_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DifficultyLevel): DifficultyLevel {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_LearningSession_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LearningSession): LearningSession {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_MessageRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageRole): MessageRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ProgressSummary_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProgressSummary): ProgressSummary {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_SkillLevel_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SkillLevel): SkillLevel {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Topic_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Topic): Topic {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserProgress_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProgress): UserProgress {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProgress]): UserProgress | null {
    return value.length === 0 ? null : from_candid_UserProgress_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Quiz]): Quiz | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Topic]): Topic | null {
    return value.length === 0 ? null : from_candid_Topic_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TopicCompletion]): TopicCompletion | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: _UserId;
    badges: Array<_Badge>;
    topicsCompleted: Array<_TopicId>;
    longestStreak: bigint;
    totalPoints: bigint;
    lastActivityAt: _Timestamp;
    currentStreak: bigint;
}): {
    userId: UserId;
    badges: Array<Badge>;
    topicsCompleted: Array<TopicId>;
    longestStreak: bigint;
    totalPoints: bigint;
    lastActivityAt: Timestamp;
    currentStreak: bigint;
} {
    return {
        userId: value.userId,
        badges: from_candid_vec_n13(_uploadFile, _downloadFile, value.badges),
        topicsCompleted: value.topicsCompleted,
        longestStreak: value.longestStreak,
        totalPoints: value.totalPoints,
        lastActivityAt: value.lastActivityAt,
        currentStreak: value.currentStreak
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SessionId;
    startedAt: _Timestamp;
    messages: Array<_ChatMessage>;
    userId: _UserId;
    isActive: boolean;
    updatedAt: _Timestamp;
    topicId: _TopicId;
}): {
    id: SessionId;
    startedAt: Timestamp;
    messages: Array<ChatMessage>;
    userId: UserId;
    isActive: boolean;
    updatedAt: Timestamp;
    topicId: TopicId;
} {
    return {
        id: value.id,
        startedAt: value.startedAt,
        messages: from_candid_vec_n18(_uploadFile, _downloadFile, value.messages),
        userId: value.userId,
        isActive: value.isActive,
        updatedAt: value.updatedAt,
        topicId: value.topicId
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    content: string;
    role: _MessageRole;
    timestamp: _Timestamp;
}): {
    content: string;
    role: MessageRole;
    timestamp: Timestamp;
} {
    return {
        content: value.content,
        role: from_candid_MessageRole_n21(_uploadFile, _downloadFile, value.role),
        timestamp: value.timestamp
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    averageAccuracy: bigint;
    badges: Array<_Badge>;
    quizAttemptCount: bigint;
    topicsCompletedCount: bigint;
    totalPoints: bigint;
    weakAreas: Array<_WeakArea>;
    currentStreak: bigint;
}): {
    averageAccuracy: bigint;
    badges: Array<Badge>;
    quizAttemptCount: bigint;
    topicsCompletedCount: bigint;
    totalPoints: bigint;
    weakAreas: Array<WeakArea>;
    currentStreak: bigint;
} {
    return {
        averageAccuracy: value.averageAccuracy,
        badges: from_candid_vec_n13(_uploadFile, _downloadFile, value.badges),
        quizAttemptCount: value.quizAttemptCount,
        topicsCompletedCount: value.topicsCompletedCount,
        totalPoints: value.totalPoints,
        weakAreas: value.weakAreas,
        currentStreak: value.currentStreak
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TopicId;
    title: string;
    difficulty: _DifficultyLevel;
    createdAt: _Timestamp;
    description: string;
    category: string;
}): {
    id: TopicId;
    title: string;
    difficulty: DifficultyLevel;
    createdAt: Timestamp;
    description: string;
    category: string;
} {
    return {
        id: value.id,
        title: value.title,
        difficulty: from_candid_DifficultyLevel_n29(_uploadFile, _downloadFile, value.difficulty),
        createdAt: value.createdAt,
        description: value.description,
        category: value.category
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    learningGoals: string;
    name: string;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    skillLevel: _SkillLevel;
}): {
    learningGoals: string;
    name: string;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    skillLevel: SkillLevel;
} {
    return {
        learningGoals: value.learningGoals,
        name: value.name,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        skillLevel: from_candid_SkillLevel_n6(_uploadFile, _downloadFile, value.skillLevel)
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    streak: null;
} | {
    perfectScore: null;
} | {
    quizMaster: null;
} | {
    firstSteps: null;
}): Badge {
    return "streak" in value ? Badge.streak : "perfectScore" in value ? Badge.perfectScore : "quizMaster" in value ? Badge.quizMaster : "firstSteps" in value ? Badge.firstSteps : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: null;
} | {
    assistant: null;
}): MessageRole {
    return "user" in value ? MessageRole.user : "assistant" in value ? MessageRole.assistant : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    easy: null;
} | {
    hard: null;
} | {
    medium: null;
}): DifficultyLevel {
    return "easy" in value ? DifficultyLevel.easy : "hard" in value ? DifficultyLevel.hard : "medium" in value ? DifficultyLevel.medium : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
}): SkillLevel {
    return "intermediate" in value ? SkillLevel.intermediate : "beginner" in value ? SkillLevel.beginner : "advanced" in value ? SkillLevel.advanced : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Badge>): Array<Badge> {
    return value.map((x)=>from_candid_Badge_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatMessage>): Array<ChatMessage> {
    return value.map((x)=>from_candid_ChatMessage_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Topic>): Array<Topic> {
    return value.map((x)=>from_candid_Topic_n27(_uploadFile, _downloadFile, x));
}
function to_candid_SkillLevel_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SkillLevel): _SkillLevel {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    learningGoals: string;
    name: string;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    skillLevel: SkillLevel;
}): {
    learningGoals: string;
    name: string;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    skillLevel: _SkillLevel;
} {
    return {
        learningGoals: value.learningGoals,
        name: value.name,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        skillLevel: to_candid_SkillLevel_n35(_uploadFile, _downloadFile, value.skillLevel)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SkillLevel): {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
} {
    return value == SkillLevel.intermediate ? {
        intermediate: null
    } : value == SkillLevel.beginner ? {
        beginner: null
    } : value == SkillLevel.advanced ? {
        advanced: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
